Все задания рекомендуется делать вручную, проверяя полученные результаты через NumPy.

__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    


а) Число столбцов матрицы А=2, число строк в матрице В=4 , значит умножение матриц АВ  не определено.

Число столбцов матрицы В=2, число строк в матрице А=4, значит умножение матриц ВА не определено.

б) Число столбцов матрицы А=5, число строк в матрице В=5 , значит умножение матриц АВ  определено. Размерность $AВ$ — матрица $2\times 3$

Число столбцов матрицы В=3, число строк в матрице В=2, значит умножение матриц ВА не определено.

в) Число столбцов матрицы А=3, число строк в матрице В=3 , значит умножение матриц АВ  определено. Размерность $AВ$ — матрица $8\times 8$

Число столбцов матрицы В=8, число строк в матрице А=, значит умножение матриц ВА определено. Размерность $ВА$ — матрица $3\times 3$

г) Так как, $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$. Следовательно  размерность $ВА$ и $АВ$ — матрица $4\times 4$

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$



$$A\cdot B=\begin{pmatrix}
1\cdot4+-2\cdot0 & 1\cdot(-1)+2\cdot5\\  
3\cdot4+0\cdot0 & 3\cdot(-1)+0\cdot5 
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$$


$$B\cdot A=\begin{pmatrix}
4\cdot1+(-1)\cdot3 & 4\cdot(-2)+(-1)\cdot0\\  
0\cdot1+5\cdot3 & 0\cdot(-2)+5\cdot0 
\end{pmatrix}=\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}.$$

In [12]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BA
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    


$$3А- 2В + 4С = 
3\begin{pmatrix}
1 & 7 \\ 
3 & -6\\ 
\end{pmatrix} - 2\begin{pmatrix}
0 & 5 \\ 
2 & -1\\ 
\end{pmatrix} + 4\begin{pmatrix}
2 & -4 \\ 
1 & 1\\ 
\end{pmatrix} = \begin{pmatrix}
3 & 21 \\ 
9 & -18\\ 
\end{pmatrix} - \begin{pmatrix}
0 & 10 \\ 
4 & -2\\ 
\end{pmatrix} + \begin{pmatrix}
8 & -16 \\ 
4 & 4\\ 
\end{pmatrix} = \begin{pmatrix}
11 & -5 \\ 
9 & -12\\ 
\end{pmatrix}$$

In [2]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'3A - 2B + 4C =\n{3 * A - 2 * B + 4 * C}\n')

3A - 2B + 4C =
[[ 11  -5]
 [  9 -12]]



__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.




$$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\  
2 & 3
\end{pmatrix}, \;A^{T}=\begin{pmatrix}
4 & 3 & 2\\ 
1 & -2 & 3
\end{pmatrix}.$$

$$A\cdot A^{T} =\begin{pmatrix}
4 & 1\\ 
5 & -2\\  
2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 3 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\  
5\cdot4+(-2)\cdot1 & 5\cdot5+(-2)\cdot(-2) & 5\cdot2+(-2)\cdot3\\  
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}.$$

$$A^{T}\cdot A =\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1\\
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot4+5\cdot5+2\cdot2 & 4\cdot1+5\cdot(-2)+2\cdot3\\  
1\cdot4+(-2)\cdot5+3\cdot2 & 1\cdot1+(-2)\cdot(-2)+3\cdot3
\end{pmatrix}=\begin{pmatrix}
45 & 0 \\
0 & 14
\end{pmatrix}.$$

In [13]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A_T = A.T

print(f'A^T =\n{A_T}\n')
print(f'A * A^T =\n{np.dot(A, A_T)}\n')
print(f'A^T * A =\n{np.dot(A_T, A)}\n')

A^T =
[[ 4  5  2]
 [ 1 -2  3]]

A * A^T =
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A^T * A =
[[45  0]
 [ 0 14]]



__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [4]:
class Matrix:
    """
    Класс для описания объекта "матрица"
    """

    def __init__(self, data):
        """
        Конструктор класса
        :param data: [[a11, a12, a13], [a21, a22, a23], ... ] список строк, где каждая строка тоже список
        """
        # Множество всех размеров строк
        rows_sizes = set([len(row) for row in data])
        
        # Матрица определяется только в том случае, если все строки имеют одинаковое число элементов
        self.data = data if len(rows_sizes) == 1 else []

    def __str__(self):
        rows_str = ['\t'.join(map(str, row)) for row in self.data]
        return '\n'.join(rows_str)

    def __add__(self, other):
        if self.is_size_equal(other):
            result = [list(map(lambda x, y: x + y, self.data[i], other.data[i])) for i in range(len(self.data))]
            return Matrix(result)
        else:
            return None
    
    def __mul__(self, other):
        # Если матрицы не согласованы, то умножение не определено
        if self.columns_count != other.rows_count:
            return None
        
        self_rows = len(self.data)
        other_rows = len(other.data)
        other_columns = len(other.data[0])
        
        result = [[None for _ in range(other_columns)] for _ in range(self_rows)]
        for i in range(self_rows):
            for j in range(other_columns):       
                result[i][j] = sum(self.data[i][k] * other.data[k][j] for k in range(other_rows))
        return Matrix(result)

    @property
    def rows_count(self):
        return len(self.data)

    @property
    def columns_count(self):
        return len(self.data[0]) if self.data else 0
    
    def is_size_equal(self, other):
        """
        Определяет имеют ли матрицы одинаковое количество строк и столбцов
        :param other: объект класса Matrix
        :return: True, если матрицы имеют одинаковое количество строк и столбцов, иначе False
        """
        return self.rows_count == other.rows_count and self.columns_count == other.columns_count

In [14]:
# Проверим на примере задания 4
A = Matrix([[4, 1], [5, -2], [2, 3]])
A_T = Matrix([[4, 5, 2], [1, -2, 3]])

print(f'A = \n{A}\n')
print(f'A_T = \n{A_T}\n')

print(f'A + A =\n{A + A}\n')
print(f'A_T + A_T =\n{A_T + A_T}\n')
print(f'A * A_T =\n{A * A_T}\n')
print(f'A_T * A =\n{A_T * A}\n')

A = 
4	1
5	-2
2	3

A_T = 
4	5	2
1	-2	3

A + A =
8	2
10	-4
4	6

A_T + A_T =
8	10	4
2	-4	6

A * A_T =
17	18	11
18	29	4
11	4	13

A_T * A =
45	0
0	14



Все задания рекомендуется выполнять вручную, проверяя полученные результаты с использованием NumPy.

__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sinx^2-cosx^2 = 1$$



   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4\begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix} = 4(5\cdot9-1\cdot0) = 180$$


$$A\cdot A^{T} =\begin{pmatrix}
4 & 1\\ 
5 & -2\\  
2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 3 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4\cdot4+1\cdot1 & 4\cdot5+1\cdot(-2) & 4\cdot2+1\cdot3\\  
5\cdot4+(-2)\cdot1 & 5\cdot5+(-2)\cdot(-2) & 5\cdot2+(-2)\cdot3\\  
2\cdot4+3\cdot1 & 2\cdot5+3\cdot(-2) & 2\cdot2+3\cdot3
\end{pmatrix}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4 \\
11 & 4 & 13
\end{pmatrix}.$$
    


   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = \begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix} - 2\begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix} + 3\begin{vmatrix}
4 & 5\\ 
7 & 8 
\end{vmatrix} = (45-48)-2(36-42)+3(32-35)=0 $$




__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;

   По свойству определителя для двух квадратных матриц одинакового размера


   $det(A^{2})$ = det A det B;

   Следовательно: 

   $det(A^{2})$ = $(det A)^{2} = 16$


   


   б) $det(A^{T})$;
    
   Определитель транспонированной матрицы равен определителю исходной:

   $$detA^{T}=detA.$$

Следовательно 

 $det(A^{T}) = 4$

  в) $det(2A)$.


  По свойству определителя умножение строки на число приведет к умножению матрицы на то же число. По условию каждая строка матрицы умножается на два, тогда

$det(2A) = 2^n det A = 2^n\cdot4$


In [15]:
# Проверим на примере произвольной невырожденной матрицы размерности 3
A = np.array([[4, 0, 0], [0, 1, 0], [0, 0, 1]])

print(f'det A = {np.linalg.det(A)}')
print(f'dim A = {A.shape}\n')

print(f'а) det A^2 = {np.linalg.det(np.linalg.matrix_power(A, 2))}')
print(f'б) det A^T = {np.linalg.det(A.T)}')
print(f'в) det 2A = {np.linalg.det(2 * A)}')

det A = 4.0
dim A = (3, 3)

а) det A^2 = 15.999999999999998
б) det A^T = 4.0
в) det 2A = 32.0


__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица называется сингулярной или вырожденной, если её определитель равен нулю.

Первая и вторая строки этой матрицы линейно зависимы, поэтому определитель равен 0. Проверим это, вычислим определитель

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix} = -2\begin{pmatrix}
-14 & 6\\ 
7 & 13
\end{pmatrix} -7 \begin{pmatrix}
4  & 6\\ 
-3 & 13
\end{pmatrix} -3\begin{pmatrix} 
4 & -14\\ 
-3 & 7
\end{pmatrix} =-2(-182-42)-7(52+18)-3(28-42)=448-490+42=0$$


__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

Вычтем из второй строки первую строку, а из третьей - первую строку, умноженную на 2, получим

$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
0 & -1 & -2
\end{pmatrix};$

Третья строка - линейная комбинация первых двух строк, поэтому ее можно отбросить, получим

$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix};$

Таким образом ранг матрицы равен 2.

In [16]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2




   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

Переставим первую и четвертую строки местами

$\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
0 & 0 & 2 & 1
\end{pmatrix}$

Вычтем из третьей строки вторую строку, умноженную на 2, а из четвертой - вторую строку получим

$\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 0 & -1\\ 
0 & 0 & 0 & -1
\end{pmatrix}$

Четвертая строка - линейная комбинация первых двух строк, поэтому ее можно отбросить, получим

$\begin{pmatrix}
2 & 3 & 5 & 6\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 0 & -1
\end{pmatrix}$

Таким образом ранг матрицы равен 3.

In [17]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'б) rank A = {np.linalg.matrix_rank(A)}')

б) rank A = 3
