## Практическое задание. Часть 1

__1.__ Решите систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$



In [24]:
import numpy as np
import scipy.linalg

def gauss_method(A, b, n):
    rnk_A = np.linalg.matrix_rank(A)
    rnk_Ab = np.linalg.matrix_rank(np.hstack((A, b)))
    if  rnk_A == rnk_Ab == n:
        return 'Cистема имеет единственное решение'
    elif (rnk_A == rnk_Ab) and (rnk_A < n):
        return 'Cистема имеет бесконечное количество решений'
    elif rnk_A < rnk_Ab:
        return 'Cистема несовместна'

In [25]:
A = np.array([[1, 1, -1, -2], [2, 1, -1, 1], [1, 1, -3, 1]])
b = np.array([0, -2, 4]).reshape(-1, 1)
gauss_method(A, b, 4)

'Cистема имеет бесконечное количество решений'

__2.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    




In [26]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, 17, 0]).reshape(-1, 1)
gauss_method(A, b, 3)

'Cистема имеет единственное решение'

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
 


In [27]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5]).reshape(-1, 1)
gauss_method(A, b, 3)

'Cистема несовместна'

  в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [28]:
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2]).reshape(-1, 1)
gauss_method(A, b, 3)

'Cистема имеет бесконечное количество решений'

__3.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$



In [29]:
def task_2(A, b):
    rank_A = np.linalg.matrix_rank(A)
    rank_A_ = np.linalg.matrix_rank(np.column_stack((A, b)))
    n = A.shape[1]
    print(f'Ранк матрицы = {rank_A}')
    print(f'Ранк расширенной матрицы = {rank_A_}')
    print(f'Количество неизвестных = {n}')
    if rank_A == rank_A_ == n:
        print('СЛУ имеет единисвенное решение')
    elif rank_A == rank_A_ < n:
        print('СЛУ имеет бесконечное число решений')
    elif rank_A < rank_A_:
        print('СЛУ несовместима')
    else:
        print('К такому жизнь не готовила')

In [30]:
A = np.array([
    [1, 3, -2, 4],
    [0, 5,  0, 1],
    [0, 0,  3, 0],
    [0, 0,  0, 2]
])
b = np.array([3, 2, 4, 1])
task_2(A, b)

Ранк матрицы = 4
Ранк расширенной матрицы = 4
Количество неизвестных = 4
СЛУ имеет единисвенное решение


__4.__ Дана система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найдите соотношение между параметрами $a$, $b$ и $c$, при которых система считается несовместной.

In [31]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
b = np.array([2, 2, 2])
task_2(A, b)

Ранк матрицы = 2
Ранк расширенной матрицы = 2
Количество неизвестных = 3
СЛУ имеет бесконечное число решений


## Практическое задание. Часть 2

__1.__ Решите систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    


$$x_{i}=\frac{detA_{i}}{detA},$$

где 
 $A_{i}$ — это матрица, получаемая заменой i-го столбца на вектор-столбец свободных членов A.

 $$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & -2\\ 
3 & -4
\end{matrix}\right|
\begin{matrix}
1\\ 
7
\end{matrix}
\end{pmatrix}.$$

$$detA=(1\cdot(-4))-(3\cdot(-2))= -4+6=2$$

In [32]:
A = np.array([[1,-2], [3, -4]])
np.linalg.det(A)

2.0000000000000004

$$detA_{1}=(1\cdot(-4))-(-2)\cdot7= -4+14=10$$

In [33]:
A_1 = np.array([[1, -2], [7, -4]])
np.linalg.det(A_1)

9.999999999999998

$$detA_{1}=(1\cdot7)-1\cdot3= 7-3=4$$

In [34]:
A_2 = np.array([[1, 1], [3, 7]])
np.linalg.det(A_2)

4.0

$$x_{1}=\frac{10}{2}=5$$

In [35]:
np.linalg.det(A_1) / np.linalg.det(A)

4.999999999999998

$$x_{2}=\frac{4}{2}=2$$

In [36]:
np.linalg.det(A_2) / np.linalg.det(A)

1.9999999999999996

   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$$x_{i}=\frac{detA_{i}}{detA},$$


 $$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{matrix}\right|
\begin{matrix}
10\\
-2\\ 
1
\end{matrix}
\end{pmatrix}.$$

$$detA=2(1\cdot1-(-3)\cdot4)+1(1\cdot1-(-3)\cdot2)+5(1\cdot4-1\cdot2)= 26+7+10=43$$

In [37]:
A = np.array([[2, -1, 5], [1, 1, -3],[2, 4, 1]])
np.linalg.det(A)

42.99999999999998

In [38]:
A_1 = np.array([[10,-1, 5], [-2, 1, -3], [1, 4, 1]])
np.linalg.det(A_1)

86.00000000000004

In [39]:
A_2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
np.linalg.det(A_2)

-43.000000000000014

In [17]:
A_3 = np.array([[2,-1, 10], [1, 1, -2], [2, 4, 1]])
np.linalg.det(A_3)

42.99999999999998

In [40]:
x_1  = np.linalg.det(A_1)/ np.linalg.det(A)
x_1

2.0000000000000018

In [41]:
x_2  = np.linalg.det(A_2)/ np.linalg.det(A)
x_2

-1.0000000000000009

In [42]:
x_3  = np.linalg.det(A_3)/ np.linalg.det(A)
x_3

1.0



__2*.__ Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
  

In [43]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
U = np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])
L = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])

LU = np.dot(L, U)

print(f'A:\n{A}\n')
print(f'L:\n{L}\n')
print(f'U:\n{U}\n')
print(f'LU:\n{LU}\n')

A:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]

L:
[[1 0 0]
 [2 1 0]
 [3 4 1]]

U:
[[1 2 4]
 [0 5 4]
 [0 0 2]]

LU:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]



 б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    


In [44]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
U = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])
L = np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])

LU = np.dot(L, U)

print(f'A:\n{A}\n')
print(f'L:\n{L}\n')
print(f'U:\n{U}\n')
print(f'LU:\n{LU}\n')

A:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]

L:
[[1 0 0 0]
 [2 1 0 0]
 [3 5 1 0]
 [4 6 7 1]]

U:
[[1 1 2 4]
 [0 3 4 1]
 [0 0 3 1]
 [0 0 0 4]]

LU:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]



__3*.__ Решите систему линейных уравнений методом $LU$-разложения:

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

$$\begin{pmatrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{pmatrix}$$

In [45]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

print(f'lu:\n{lu}\n')
print(f'piv:\n{piv}\n')

A:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

b:
[ 1 -6 -5]

x:
[-1.00000000e+00  2.44249065e-16  1.00000000e+00]

Ax:
[ 1. -6. -5.]

Ax - b:
[0. 0. 0.]

lu:
[[11.          7.          5.        ]
 [ 0.81818182  2.27272727 -0.09090909]
 [ 0.18181818 -0.12        2.08      ]]

piv:
[1 2 2]

