## Практическое задание





__1.__ Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$



Чтобы число $\lambda$ было собственным значением оператора A, это число должно быть корнем характеристического уравнения оператора A.

Характеристическое уравнение матрицы A:

$$det(\textbf{A}-\lambda\textbf{I})= \begin{vmatrix}
-1 -\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = \lambda^2 -(-1+6)\cdot\lambda+(-1\cdot6-(-6\cdot2))=\lambda^2-5\lambda+6=0.$$


Решим квдратное уравнение:

$$\lambda^2-5\lambda+6=0.$$

$$D=b^2-4ac=25-24=1$$

$$\lambda_{1,2}=\frac{-b\pm\sqrt{D}}{2a}=\frac{5\pm1}{2}$$

Значит корни характеристического уравнения:

$$\lambda_{1}=3$$

$$\lambda_{2}=2$$

являются собственными значениями матрицы A.

Найдем собственные векторы, подставив полученные собственные значения в выражение $$(\textbf{A}-\lambda\textbf{I})x=0$$.


$$(\textbf{A}-\lambda\textbf{I})x=\begin{pmatrix}
-1 & -6\\ 
2 & 3
\end{pmatrix}\cdot\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=0$$

1. $$\lambda_{1}=2$$

$$\begin{cases}
-x_{1}-6\cdot x_{2}= 2\cdot x_{1}, \\
2\cdot x_{1}+6\cdot x_{2}= 2\cdot x_{2},
\end{cases}$$ 

$$\begin{cases}
-3\cdot x_{1}= 6\cdot x_{2}, \\
2\cdot x_{1}= -4\cdot x_{2},
\end{cases}$$ 

2. $$\lambda_{1}=3$$

$$\begin{cases}
-x_{1}-6\cdot x_{2}= 3\cdot x_{1}, \\
2\cdot x_{1}+6\cdot x_{2}= 3\cdot x_{2},
\end{cases}$$ 

$$\begin{cases}
-4\cdot x_{1}= 6\cdot x_{2}, \\
2\cdot x_{1}= -3\cdot x_{2},
\end{cases}$$ 

Ответ: cобственные значения: 

$$\lambda _{1}=3,  \lambda _{2}=2$$



In [2]:
import numpy as np
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)


In [3]:
print ("Собственные числа:\n", w)
print ("Собственные векторы:\n", v)

Собственные числа:
 [2. 3.]
Собственные векторы:
 [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей:

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Покажите, что __любой__ вектор считается для него собственным.



Возьмем некоторый вектор, сотоящий из произвольных констант:

$$х=\begin{pmatrix}
С_{1}\\ 
С_{2}
\end{pmatrix}.$$

и предположим, что этот вектор x является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $$\lambda$$, при котором $$A_{x}=\lambda_{x}$$, то есть:

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}\begin{pmatrix}
С_{1}\\ 
С_{2}
\end{pmatrix}=\lambda\begin{pmatrix}
С_{1}\\ 
С_{2}
\end{pmatrix} $$

Из этого следует:

$$\begin{cases}
-C_{1}= -C_{1}\cdot \lambda \\
-C_{2}= -C_{2}\cdot \lambda
\end{cases}\Rightarrow \lambda = -1$$ 

Ответ: любой вектор является собственным с собственным значением $$\lambda = -1$$ 

In [4]:
b = np.array([[-1, 0], [0, -1]])
n, m = np.linalg.eig(b)

In [5]:
print ("Собственные числа:\n", n)
print ("Собственные векторы:\n", m)

Собственные числа:
 [-1. -1.]
Собственные векторы:
 [[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установите, считается ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}\begin{pmatrix}
1 \\ 
1 
\end{pmatrix} = \lambda \begin{pmatrix}
1 \\ 
1 
\end{pmatrix}$$

Из этого следует:

$$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$$

Ответ: вектор $x=(1,1)$ считается собственным вектором линейного оператора, заданного матрицей A, и его собственное значение составляет $$\lambda=2$$

In [6]:
c = np.array([[1, 1], [-1, 3]])
f, g = np.linalg.eig(c)
 
print ("Собственные числа:\n", f)
print ("Собственные векторы:\n", g)

Собственные числа:
 [2.00000002 1.99999998]
Собственные векторы:
 [[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


**4.** Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установите, считается ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.


$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

$$\Rightarrow
\begin{cases}
-9 = 3\cdot\lambda\\ 
9 = -3\cdot \lambda\\
-12 = -4 \cdot\lambda
\end{cases}
\Rightarrow 
\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3
\end{cases}$$

Ответ:  вектор $x=(3,-3,-4)$ не является собственным вектором линейного оператора, заданного матрицей $A$.

In [7]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
